### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by calcyu** [eduardoboucas/staticman#59] opened 2016-11-22 15:21 UTC
POST:https://api.staticman.net/v2/entry/calcyu/calcyu.github.io/master/comments
RESPONSE:
{"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/git/refs/#create-a-reference\"}"}

**Comment by calcyu** [comment] 2016-11-22 15:26
Originally I did not run
https://api.staticman.net/v2/connect/calcyu/calcyu.github.io

**Comment by eduardoboucas** [comment] 2016-11-22 16:11
Are you saying it's working fine now?

**Comment by calcyu** [comment] 2016-11-22 23:14
Yes,thanks

**Comment by simonv3** [comment] 2016-11-23 00:29
I'm getting a similar error but it's not resolved by connecting staticman to our repository (via accessing the URL). 

Repo is here: https://github.com/opensourcedesign/opensrcdesignjobs

Repo it's trying to post to is here: https://github.com/opensourcedesign/jobs

It posts to URL: https://api.staticman.net/v2/entry/opensourcedesign/jobs/gh-pages/
And this spits out: 

```
{"code":404,"status":"Not Found","message":"{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3\"}"}
```

**Comment by eduardoboucas** [comment] 2016-11-24 15:52
(Didn't forget about this, will look into it asap)

**Comment by simonv3** [comment] 2016-11-24 16:48
@eduardoboucas Thanks! There's no big rush on our end :)

It's also entirely possible that the problem is on our end in the implementation.

**Comment by eduardoboucas** [comment] 2016-11-24 17:36
@simonv3 do you mind if I use the bot to change your Staticman config file?

**Comment by simonv3** [comment] 2016-11-24 18:08
@eduardoboucas Not at all. I can also give you access to the repo if you prefer.

**Comment by eduardoboucas** [comment] 2016-11-24 18:23
You have a few issues with your implementation:

1. In [here](https://github.com/opensourcedesign/opensrcdesignjobs/blob/gh-pages/index.html#L25), the name of the repository should be `opensrcdesignjobs` and not `jobs`
1. Also in that line, you're missing the name of the property, which is the object under which all the configuration parameters are nested under in your config file. In this case, it will be `comments`, so the URL will be https://api.staticman.net/v2/entry/opensourcedesign/opensrcdesignjobs/gh-pages/comments
1. Your config is using `allowedOrigins` but you're not sending a `options[origin]` field. I've disabled `allowedOrigins` in your config, since you only need it if you're using email notifications
1. You have a `notifications` block, but the API keys aren't filled in, so it's causing an error (I will remove this from the sample config file)
1. You have a block of `requiredFields` that don't exist in your form. I've commented this out.
1. Your `path` field in the config is using `options.slug`, which corresponds to a `options[slug]` field which you're not sending in your form

Please have a look at the outstanding issues and let me know if you manage to get it working.

**Comment by simonv3** [comment] 2016-11-24 19:39
Awesome! This looks like it works.

I'm going to have to look into sluggifying our title through JavaScript I guess?

**Comment by eduardoboucas** [comment] 2016-11-24 23:27
You're using Jekyll, so have a look at the [available variables](https://jekyllrb.com/docs/permalinks/) (one of them is `slug`).

I will close this issue, but feel free to reopen if you run into any problems.

**Closed as completed by eduardoboucas** 2016-11-24 23:27 UTC
