### ISSUE TITLE
Application error while inviting staticmap

### ISSUE THREAD

**Issue by tomasparks** [eduardoboucas/staticman#302] opened 2019-07-05 10:34 UTC
I am getting Application error while inviting staticmap

https://api.staticman.net/v2/connect/tomasparks/website

`Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail`

**Comment by VincentTam** [comment] 2019-07-05 11:38
You've also commented in exactly the same issue #296.  Please consider closing this in favor of #296 in order to keep the discussion focused.

**Comment by alexwaibel** [comment] 2019-11-08 02:55
Duplicate of #296

**Closed as completed by alexwaibel** 2019-11-08 02:55 UTC
Labels: bug
