### ISSUE TITLE
Random fields are being added

### ISSUE THREAD

**Issue by fbnlsr** [eduardoboucas/staticman#209] opened 2018-06-12 09:48 UTC
Sometimes, when I get a PR from Staticman (I use it for my comment system on my blog), I get fields that should not be present.

https://github.com/fbnlsr/primative.net/pull/55

There should not be any `layout`, `timestamp`, `message` or `tags` in this generated file.

**Comment by chmac** [comment] 2018-06-13 09:09
Duplicate of #176.

**Closed as completed** 2018-06-13 12:45 UTC
