### ISSUE TITLE
reCaptcha problem when not validated

### ISSUE THREAD

**Issue by Jeern** [eduardoboucas/staticman#235] opened 2018-09-24 20:27 UTC
I have implemented reCaptcha in my Hugo site using this:  https://github.com/eduardoboucas/staticman-recaptcha

Its nice and it works, when I Click the reCaptcha radio button.

But when I do not click the button (i.e. I simulate being a SPAM bot) I do not get nice feedback, but only this json Object:

{"success":false,"message":"reCAPTCHA: The response parameter is invalid or malformed","rawError":{"_smErrorCode":"invalid-input-response"},"errorCode":"RECAPTCHA_INVALID_INPUT_RESPONSE"}

Is this an error in Staticman ? or is it implied that I have to parse that response myself ? If that is the case I think the problem is with the documentation of Staticman :) 

Minor problem but I thought you might like to know :) and keep up the great work !

**Comment by VincentTam** [comment] 2019-07-05 09:52
Duplicate of #223.

**Closed as completed** 2019-11-08 09:01 UTC
Labels: bug
