### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by Uzay-G** [eduardoboucas/staticman#320] opened 2019-11-11 20:14 UTC
I was following the documentation instructions and noticed there is no staticmanapp collaborator. I then hunched my way through the issues to understand a static man Github app has been created. It's difficult for new users like me to understand how things work if the documentation is old. 

I'm lost on how to get the tool set up properly.

**Comment by alexwaibel** [comment] 2019-11-12 06:14
Duplicate of #312

**Comment by alexwaibel** [comment] 2019-11-12 06:28
@Uzay-G I've only very recently taken over maintenance of this project so still lots of work to do. The public instances seem to be very unreliable as they're hosted in a free heroku instance and lots and lots of people try to use them. I'm aware of how outdated and confusing the docs are and updating them is on my list once I can verify the application is working properly.

For now, I have been able to get this working on a test instance. For the best results, I would recommend hosting your own instance of [my patched dev branch](https://github.com/alexwaibel/staticman/tree/dev). I would recommend only using personal access token authentication with GitHub as well as /v2/ of the Staticman endpoints and not /v3/ for now, as I haven't gotten to testing the rest yet. You can quite easily host your instance in Heroku. The abridged version is:

1. Fork my dev branch to your own repo
2. Create a free Heroku account and link to your GitHub
3. Create a new Heroku app and select the options to deploy from GitHub then select your fork repo
4. Create a new GitHub account to run your bot. In this account, generate a personal access token in dev settings and use this in your Heroku config for your own Staticman instance.
5. In Heroku settings for your deployed app, set your config vars using [these API config options](https://staticman.net/docs/api)
6. Follow [this guide](https://staticman.net/docs/index.html) but using your own API on Heroku instead of the public staticman instance.

Best of luck. Let me know if you need any further help and I'll do my best to point you in the right direction.

**Comment by alexwaibel** [comment] 2019-12-07 01:59
Closing this issue, as I believe I've addressed your question. Feel free to comment if you have further questions!

**Closed as completed by alexwaibel** 2019-12-07 01:59 UTC
Labels: question
