### ISSUE TITLE
[documentation] how to use staticman on gitlab?

### ISSUE THREAD

**Issue by robinmoussu** [eduardoboucas/staticman#293] opened 2019-05-18 16:08 UTC
Staticman seems usable with gitlab, but I wasn't able to understand how to do it. I think that the [main documentation](https://staticman.net/docs/) should be updated (or at least points to another page) where it explains how to use gitlab.

@VincentTam Do you think it could be possible that you describe what you did on your [test](https://gitlab.com/VincentTam/test-hugo-staticman). I'm also using hugo, so it would be highly welcome.

**Comment by VincentTam** [comment] 2019-05-18 17:59
@robinmoussu I've already done that in [my GitLab + Staticman tutorial](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/1/) in September, and here's a more refined version: https://gitlab.com/VincentTam/bhdemo#beautiful-hugo-with-staticman-comment-reply.  Nonetheless, I recommend [using Framagit](https://math.meta.stackexchange.com/a/29462/290189) (see last section), another GitLab instance, instead of GitLab.com for performance reasons.

Here's some instructions from others for GitLab + Staticman:

1. [*Using jekyll*](https://satishramjee.gitlab.io/blogging/using-jekyll/#comments)
2. [*New year, new blog*](https://zcrc.me/misc/2019/01/11/new-year-new-blog.html#d7519030-15ed-11e9-9c12-85e67745fad5) (Comment no. 2)

Judging from PR's for documentation changes such as #256, #261, #266, #281, I think writing a separate blog post would be a better choice for the moment.  You may consider contributing one if you like.

Remarks: #283 shows the value of creating and using alternate API instances : in case of unnotified updates of the NodeJS app, your personal site's commenting service _won't_ suddenly get broken.  You can merge and deploy the updates/PR's on your test GitHub/GitLab pages until you're satisfied.  Due to the emergence of alternate API instances implementing this NodeJS app at _different_ versions, it's more difficult to converge to a common unified guide.  Nevertheless, I'm always pingable here, and my blog and test sites on [GitHub](https://git.io/bjsm18), [GitLab](https://gitlab.com/users/staticmanlab/contributed) & [Framagit](https://framagit.org/staticman-gitlab-pages).

**Comment by robinmoussu** [comment] 2019-05-18 21:28
Thanks for the quick answer. I tried again, but without success.

I obviously don't understand something, so I tried to sum-up what I understand, and what I tried.

From what I understand, I should add in each blog post a form to be able to send a comment. I think that it's just a configuration somewhere, and when the gitlab CI build my blog, it will add that form automatically at the end of each blog post.
When a user fill that form and click on the "submit" button, a request to a staticman instance should be send (for example to the framasoft instance). The staticman instance will then create a pull request on the gitlab of my blogpost, that should be accepted automatically (if I comments are not moderated). To do that the gitlab user of the framasoft instance of staticman should be added as a developper. That pull request will add a new file in `data/comments`, and trigger a rebuild of the site (like any PR). Once rebuilded, the blog post will contains the post + the form + the comment.

1. I don't understand how the form (to be able to send the comments) is generated.
2. I cloned https://gitlab.com/VincentTam/bhdemo#beautiful-hugo-with-staticman-comment-reply then did `hugo server` to test locally. I only have a blank page on my localhost instance, witch is quite impractical for testing. I force pushed it on my blog, and (after the CI builded it), I got the blog posts with the comments. I tried to add a new comment, without success. For obvious reason I reverted this push to the normal content of my blog.
3. I'm not sure that I gave the correct right to the framasoft bot. What is it's username?

**Comment by VincentTam** [comment] 2019-05-18 21:56
> I think that it's just a configuration somewhere, and when the gitlab CI build my blog, it will add that form automatically at the end of each blog post.

The Go-HTML template file(s) under `layouts/partials` do the job.

* * *

Before I proceed, it's better to give a quick response to clarify the roles of my two public GitLab instances.

| "name" | "public GitLab instance" | "public Framagit instance" |
| --- | --- | --- |
| GitLab instance served | GitLab.com | Framagit |
| `gitlabBaseUrl` | https://gitlab.com | https://framagit.org |
| GitLab Bot | [staticmanlab](https://gitlab.com/staticmanlab) | [staticmanlab1](https://framagit.org/staticmanlab1) |
| `githubBaseUrl` | https://github.com | https://github.com |
| API URL | https://staticman3.herokuapp.com | https://staticman-frama.herokuapp.com |

AFAIK, `gitlabBaseUrl` can only take one GitLab instance.  Both of them are run on a Heroku free dyno, which sleeps after 30 minutes of inactivity and has a 20s wake-up time.  Heroku's free dyno _isn't_ for production.  I've chosen it since the original purpose is to test the GitLab support as well as the unmerged #231.

Remarks: The user name **staticmanlab** has been taken up by someone else on Framagit, so I have to append the digit '1'.

**Comment by VincentTam** [comment] 2019-05-18 22:49
Re-reading my "refined" guide, I'm shocked that two crucial steps are missing.  I'll fix this after answering your questions.

> The staticman instance will then create a pull request on the gitlab of my blogpost, that should be accepted automatically (if I comments are not moderated)

| `moderation` | `true` | `false` |
| --- | --- | --- |
| Staticman API server's action | create Merge request | directly push against `branch` |
| authorization needed | developer | developer + right to [push against protected branch](https://docs.gitlab.com/ee/user/project/protected_branches.html) |

> That pull request will add a new file in data/comments, and trigger a rebuild of the site (like any PR). Once rebuilded, the blog post will contains the post + the form + the comment.

That's the result of several things done well:

1. Staticman (as a NodeJS app) (relay HTML `<form>` data to GitHub/GitLab repo according to the `path` found in root-level `staticman.yml`)
2. CD/CI (for automatic rebuild)
3. Site theme('s Staticman integration) (for displaying static comments)

Items (1) and (3) require a config file.  I call the former "(git) repo config", and the later "site config" for clarity.

Staticman (this Git repo, as a a NodeJS app), is only responsible for (1).  As long as the API server can transmit the generated data files into the `path` specified in root-level `staticman.yml`, then step (1) is good.  In case of problems in (3), it's a problem with the site theme.

* * *

Let's get back to your questions.

1. To generate an HTML form by hand, you may try the HTML `<form>` element on W3 School's tutorial.
2. Staticman API servers communicate with remote Git servers, not local Git repos.
3. Please see the table in the above comment.

**Comment by VincentTam** [comment] 2019-05-19 08:03
> Thanks for the quick answer. I tried again, but without success.

@robinmoussu Please include the link to your site as well as your source code, so that other users, apart from me, may also offer a helping hand.  Please consider giving the error message and the error code so that your error can be reproduced by others.

After resting for a night, I've reminded myself that I haven't yet clearly addressed the quoted sentence.  The [GitLab repo for your blog](https://gitlab.com/robinmoussu/blog) has _no root-level_ `staticman.yml`.  That's why a Staticman API instance _can't_ interact with your repo.

To understand how Staticman (as a NodeJS app) works, I recommend the original demo repo https://gitlab.com/ntsim/test-staticman (require GitLab login to view) posted in https://github.com/eduardoboucas/staticman/pull/219#issuecomment-417857360.  I recommend reading the comments by Nicolas Tsim, the author of that PR, as a _reference_, especially the top of the page.  However, the setup guide mixes up two things: server-side setup and client-side setup.  That's why I've written two separate articles in my blog to make things clear for *non*-developers like me.  In addition, the original comments might contain [careless mistakes](https://github.com/eduardoboucas/staticman/pull/219#issuecomment-419676635), since our mind might get tired after hours of coding, thinking and writing.

Apart from the [lack of repo config](https://gitlab.com/search?utf8=%E2%9C%93&search=staticman&group_id=&project_id=7544454&search_code=true&repository_ref=master) in the GitLab repo for your blog, your site template (customized Beautiful Hugo) lacks Go-HTML partial template(s) for Staticman comments display.  Despite the [offiical GitLab Pages + Hugo demo](https://gitlab.com/pages/hugo) embed Hugo themes as a subdirectory, it's better to follow [Hugo's official quick start guide](https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme) and embed a Hugo theme as a [Git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) because it's not supposed to be modified as frequently as the blog's `content` folder.  This allows you to easily merge additional features and/or bug fixes in [your Hugo theme's PR](https://github.com/halogenica/beautifulhugo/pulls), such as, halogenica/beautifulhugo#225 for Archive support.  You may consider my Staticman nested comment & instant preview support halogenica/beautifulhugo#222 for the Go-HTML template needed to render Staticman comments.

**Comment by VincentTam** [comment] 2019-05-24 11:15
> 2. I cloned https://gitlab.com/VincentTam/bhdemo#beautiful-hugo-with-staticman-comment-reply then did `hugo server` to test locally. I only have a blank page on my localhost instance, witch is quite impractical for testing.

@robinmoussu I've overlooked this problem.  This is due to the lack of the `themesDir` `theme/beautifulhugo`, and that's a usage problem of `hugo server`, not a Staticman problem.  You may include the theme Beautiful Hugo by `git submodule update --init --remote --recursive`.  Due to the file `.gitmodules`, `git submodule` will set up the `themesDir` to track [my tweaked Beautiful Hugo](https://gitlab.com/vincenttam/beautifulhugo), which includes some PR's (optional features and bug fixes) of the original theme, notably halogenica/beautifulhugo#222.

Looking back, I should have included the [`--recurse-submodules`](https://stackoverflow.com/q/3796927/3184351) in the `git clone` command in the README of my demo project.

P.S. The code written for nested Staticman integration for the theme Beautiful Hugo in the above linked PR is, in fact, unnecessarily complicated. (c.f. https://github.com/victoriadotdev/hugo-theme-introduction/pull/119#issuecomment-448613809) This has motivated me to retake [a Framagit user's abandonned work](https://framagit.org/Bridouz/bridouz.frama.io/commit/f01aca4e3267d87d15057ca596554b3a190bd45f), simplify the template code and port it into another theme [Huginn](https://framagit.org/staticman-gitlab-pages/hugo-theme-huginn).  The newly developped site should be a better demo.

Demo site: https://staticman-gitlab-pages.frama.io/huginn

**Comment by robinmoussu** [comment] 2019-05-24 11:18
Thanks a lot for the support. I'm currently moving home, and I will test that in probably 2 weeks

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by VincentTam** [comment] 2019-05-24 11:22
@robinmoussu Bon déménagement et bonne installation !

**Comment by VincentTam** [comment] 2019-06-04 22:50
@robinmoussu Here's a related [Hugo Discourse question](https://discourse.gohugo.io/t/installed-hugo-installed-template-but-localhost-1313-blank-or-error/18838) about the problem of blank page in Hugo.  I didn't (and won't) read it in details.  Perhaps you might find this informative.

**Comment by VincentTam** [comment] 2019-08-06 12:21
Update: For a documentation on how to use Staticman with GitLab, I've written an illustrated guide in the README for a recently published Hugo theme called Huginn at https://themes.gohugo.io/huginn/.

**Comment by alexwaibel** [comment] 2019-11-08 03:23
Duplicate of #312

**Closed as completed by alexwaibel** 2019-11-08 03:23 UTC
Labels: needs docs

**Comment by adamzachyang** [comment] 2025-01-01 20:39
> After resting for a night, I've reminded myself that I haven't yet clearly addressed the quoted sentence. The [GitLab repo for your blog](https://gitlab.com/robinmoussu/blog) has _no root-level_ `staticman.yml`. That's why a Staticman API instance _can't_ interact with your repo.

Just found this after trying to set up Staticman on GitLab and was exactly what I was missing. Thanks @VincentTam!
